/**
 * Flashcard Schema Definition for MongoDB
 *
 * This schema defines the structure for flashcard documents in the LinguaFlip application.
 * It includes card content, SM-2 spaced repetition data, and statistical information.
 */

/**
 * Flashcard Schema Definition
 */
export const FlashcardSchema = {
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: [
        'cardId',
        'userId',
        'front',
        'back',
        'category',
        'sm2',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        cardId: {
          bsonType: 'string',
          description: 'Unique card identifier',
        },
        userId: {
          bsonType: 'string',
          description: 'Owner user ID',
        },
        front: {
          bsonType: 'string',
          maxLength: 1000,
          description: 'Card front content',
        },
        back: {
          bsonType: 'string',
          maxLength: 1000,
          description: 'Card back content',
        },
        exampleFront: {
          bsonType: ['string', 'null'],
          maxLength: 1000,
          description: 'Example sentence in front language',
        },
        exampleBack: {
          bsonType: ['string', 'null'],
          maxLength: 1000,
          description: 'Example sentence in back language',
        },
        audioUrl: {
          bsonType: ['string', 'null'],
          description: 'Pronunciation audio URL',
          pattern: '^https?://.+',
        },
        imageUrl: {
          bsonType: ['string', 'null'],
          description: 'Illustrative image URL',
          pattern: '^https?://.+',
        },
        tags: {
          bsonType: 'array',
          items: {
            bsonType: 'string',
            maxLength: 50,
          },
          description: 'Card tags for organization',
        },
        category: {
          bsonType: 'string',
          maxLength: 100,
          description: 'Card category',
        },
        difficulty: {
          enum: ['easy', 'medium', 'hard'],
          description: 'Perceived difficulty level',
        },
        metadata: {
          bsonType: 'object',
          properties: {
            source: {
              bsonType: 'string',
              maxLength: 200,
              description: 'Content source',
            },
            createdByAI: {
              bsonType: 'bool',
              description: 'Generated by AI',
            },
            aiModel: {
              bsonType: 'string',
              maxLength: 100,
              description: 'AI model used for generation',
            },
            confidence: {
              bsonType: 'double',
              minimum: 0,
              maximum: 1,
              description: 'AI confidence score',
            },
          },
        },
        sm2: {
          bsonType: 'object',
          required: ['easeFactor', 'interval', 'repetitions', 'nextReviewDate'],
          properties: {
            easeFactor: {
              bsonType: 'double',
              minimum: 1.3,
              maximum: 2.5,
              description: 'SM-2 ease factor',
            },
            interval: {
              bsonType: 'int',
              minimum: 1,
              description: 'Current interval in days',
            },
            repetitions: {
              bsonType: 'int',
              minimum: 0,
              description: 'Successful recalls in a row',
            },
            nextReviewDate: {
              bsonType: 'date',
              description: 'Next review due date',
            },
            lastReviewed: {
              bsonType: ['date', 'null'],
              description: 'Last review timestamp',
            },
            qualityResponses: {
              bsonType: 'array',
              items: {
                bsonType: 'int',
                minimum: 0,
                maximum: 5,
              },
              description: 'Historical quality responses',
            },
            totalReviews: {
              bsonType: 'int',
              minimum: 0,
              description: 'Total review attempts',
            },
            correctStreak: {
              bsonType: 'int',
              minimum: 0,
              description: 'Current correct answers streak',
            },
            incorrectStreak: {
              bsonType: 'int',
              minimum: 0,
              description: 'Current incorrect answers streak',
            },
            isSuspended: {
              bsonType: 'bool',
              description: 'Card temporarily suspended',
            },
            suspensionReason: {
              bsonType: 'string',
              maxLength: 200,
              description: 'Reason for suspension',
            },
          },
        },
        statistics: {
          bsonType: 'object',
          properties: {
            timesCorrect: {
              bsonType: 'int',
              minimum: 0,
              description: 'Total correct responses',
            },
            timesIncorrect: {
              bsonType: 'int',
              minimum: 0,
              description: 'Total incorrect responses',
            },
            averageResponseTime: {
              bsonType: 'double',
              minimum: 0,
              description: 'Average response time in seconds',
            },
            lastDifficulty: {
              enum: ['easy', 'medium', 'hard'],
              description: 'Last reported difficulty',
            },
          },
        },
        createdAt: {
          bsonType: 'date',
          description: 'Card creation timestamp',
        },
        updatedAt: {
          bsonType: 'date',
          description: 'Card last update timestamp',
        },
        version: {
          bsonType: 'int',
          minimum: 1,
          description: 'Schema version',
        },
      },
    },
  },
};
